almastudio/urls.py
from django.contrib import admin
from django.urls import path,include,re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('', include('home.urls')),
    path('contactus/', include('contact.urls')),
    path('blog/', include('blog.urls')),
    path('forum/', include('forum.urls')),

]

blog/urls.py
from django.conf.urls import url
from django.urls import path , re_path
from .views import BlogList,Blog1


app_name = 'blog'

urlpatterns = [
    path('', BlogList.as_view()),
    path('1', Blog1.as_view()),
]

contact/urls.py
from django.conf.urls import url
from django.urls import path , re_path
from .views import Contactus


app_name = 'contact'

urlpatterns = [
    path('', Contactus.as_view()),
]

forum/urls.py
from django.conf.urls import url
from django.urls import path , re_path
from .views import Forumlist , Newtopic ,topic
from . import views

app_name = 'forum'

urlpatterns = [
    path('list', Forumlist.as_view()),
    path('newtopic', views.topic, name='topic'),

]

home/urls.py
from django.conf.urls import url
from django.urls import path , re_path
from .views import Home


app_name = 'home'

urlpatterns = [
    path('', Home.as_view()),
]

blog/models.py
# Create your models here.
from django.db import models
##
class Blog (models.Model):

    BLOG_TYPE = (
        ('Y', 'SHOW'),
        ('N', 'NO SHOW'),
    )

    blog_id = models.AutoField(primary_key=True)
    blog_type = models.CharField(max_length=1, choices=BLOG_TYPE)
    blog_title = models.CharField(max_length=50)
    blog_desc = models.CharField(max_length=1000)
    blog_text = models.TextField(default='none')
    blog_date = models.DateField(auto_now_add=True)
    blog_order = models.IntegerField(default=1)
    blog_pic = models.CharField(max_length=50,default='none')

    def __unicode__(self):
        return self.post_id

contact/models.py
from django.db import models

# Create your models here.

forum/models.py
from django.db import models

class Forum(models.Model):

    forum_id = models.AutoField(primary_key=True)
    forum_title = models.CharField(max_length=50)
    forum_text = models.TextField(default='none')
    forum_date = models.DateField(auto_now_add=True)


    def __unicode__(self):
        return self.forum_id

class Comments (models.Model):
    forum_id = models.AutoField(primary_key=True)
    comment_id = models.ForeignKey(Forum, on_delete=models.CASCADE)
    comment_title = models.CharField(max_length=50)
    comment_text = models.TextField(default='none')
    comment_date = models.DateField(auto_now_add=True)

    def __unicode__(self):
        return self.comment_id

home/models.py
from django.db import models

class Email (models.Model):

    email_id = models.AutoField(primary_key=True)
    email_name = models.CharField(max_length=50,blank=True)
    email_email = models.CharField(max_length=50)
    email_phone = models.CharField(max_length=50,blank=True)
    email_text = models.TextField(default='none',blank=True)
    email_date = models.DateField(auto_now_add=True)

    def __unicode__(self):
        return self.email_id

contact/forms.py
from django import forms
from home.models import Email

class Email(forms.ModelForm):

    class Meta:
        model = Email
        fields = ['email_name', 'email_email','email_phone' ,'email_text' ]

    def clean_email_name(self):
        data = self.cleaned_data['first_name']
        if data == 'ofer':
            raise forms.ValidationError("You must select name image!")
        return data

    def clean_email_email(self):
        data = self.cleaned_data['email_email']
        return data


from django import forms

class Contact(forms.Form):
    email_name = forms.CharField(max_length=100)
    email_phone = forms.CharField(max_length=100)
    email_text = forms.CharField(widget=forms.Textarea)
    email_email = forms.EmailField()

forum/forms.py
from django.forms import ModelForm , forms
from .models import Forum

class Newtopic(ModelForm):
    class Meta:
        model = Forum
        fields = [ 'forum_title', 'forum_text']

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get("forum_title")
        text = cleaned_data.get("forum_text")

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView,TemplateView
from .models import Blog
# Create your views here.
class BlogList(ListView):
    template_name = 'blog.html'
    model = Blog
    paginate_by = 8
     

class Blog1(TemplateView):
    template_name = '1.html'

contact/views.py
from django.shortcuts import render
from django.views.generic import FormView
from .forms import Contact
from django.core.mail import send_mail
from django.utils.decorators import method_decorator


# Create your views here.

class Contactus(FormView):
    template_name = 'contactus.html'
    form_class = Contact
    success_url = '/contactus/'


    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def sendmail(self,name, to, phone, text):
        message = 'אנו ניצור קשר בהקדם , תודה צוות django-lab.' + '   הפרטים המצורפים ' +phone + '  -  '+ text
        send_mail(
            ['תודה שפנית אלינו'],
            message,
            'oferel@zohomail.com',
            [to , 'oferel1@gmail.com'],
            fail_silently=False,
        )

    def post(self, request, *args, **kwargs):
        """
        Handle POST requests: instantiate a form instance with the passed
        POST variables and then check if it's valid.
        """
        form = self.get_form()
        if form.is_valid():

            name = form.cleaned_data['email_name']
            to = form.cleaned_data['email_email']
            phone = form.cleaned_data['email_phone']
            text = form.cleaned_data['email_text']
            self.sendmail(name, to, phone, text)
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

forum/views.py
from django.shortcuts import render ,redirect
from django.views.generic import ListView , FormView
from .models import Forum
from .forms import Newtopic



# Create your views here.
class Forumlist(ListView):
    template_name = 'forum.html'
    model = Forum
    paginate_by = 8


def topic(request):
    if request.method == "POST":
        form = Newtopic(request.POST)
        form.full_clean()
        v = form.is_valid()
        if v :
            form.save()
            return redirect('/forum/list')
    else:
        form=Newtopic()

home/views.py
from django.shortcuts import render
from blog.models import Blog
from contact.forms import Contact
import os
# Create your views here.

from django.views.generic import TemplateView


class Home(TemplateView):
    template_name = "home.html"
    blog1 = Blog.objects.get(blog_id=1)
    blog_title1 = blog1.blog_title
    blog_desc1 = blog1.blog_desc
    blog2 = Blog.objects.get(blog_id=2)
    blog_title2 = blog2.blog_title
    blog_desc2 = blog2.blog_desc
    extra_context = {'title1': blog_title1 , 'desc1': blog_desc1,'title2': blog_title2 , 'desc2': blog_desc2 , 'form':Contact}

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     result = Blog.objects.raw('select blog_id , blog_desc from blog_blog where blog_id=1')
    #     context = result
    #
    # def get_queryset(self):
    #     queryset  = Blog.objects.get(blog_id=1)
    #     #Blog.objects.raw('select blog_desc from blog_blog where blog_id=1')
    #     return queryset

blog/templates/1.html
{% extends "base.html" %}
{% load static %}
{% block header %}
<style>
.center {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
.con {
  position: relative;
  text-align: center;
  color: white;
</style>

{% endblock %}
{% block content %}
 <!--navber -->
 {% include "navblog.html" %}
  <!-- Page Header -->
<div class="con">
  <img src="{% static 'blog/django.jpg' %}" style="width:100%;">
  <div class="center">
    <h1>DJANGO</h1>
  </div>
</div>



<article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            <br>
          <p class="text-right">
            Django הינה framework של שפת פיתון המבוססת קוד פתוח ומשמשת לפיתוח מהיר, עיצוב פרגמטי, בר-תחזוקה, נקי ומאובטח, וכל זאת תוך שמירה על עקרונות פיתוח מתקדמים.
          </p>

          <h2 class="section-heading" style="text-align: right;"> ארכיטקטורת MVC</h2>

          <p class="text-right">  מכיוון ש django מבוססת Python היא נבנתה על בסיס ארכיטקטורת ה MVC המתארת טכניקה לחלוקת היישום לשלושה חלקים, מודל, תצוגה ובקר.</p>

          <p class="text-right">  ארכיטקטורה זו מאפשרת להפחית למינימום את התלות ההדדית בין החלקים השונים ומאפשרת לפתח באופן בלתי-תלוי את הרכיבים ביישום.</p>

          <blockquote class="blockquote" style="text-align: right;">
            ארכיטקטורה זו בא לידי ביטוי ב Django ע"י הרכיבים Model-View-Template<br>
              ולכן הארכיטקטורה זו  ב Django נקראת MVT.
          </blockquote>


          <h2 class="section-heading" style="text-align: right;">פילוספיית ה DRY</h2>
          <p class="text-right">
            הפילוסופיה של DRY (אל תחזור על עצמך) המתקיימת ב Django היא המסייעת למפתחים להשיג את עקרון הפיתוח המהיר.
             Django מאפשרת לעבוד על מספר רב של ישוממים מבלי לכתוב את הקוד בכל פעם מאפס.
היכולת להשתמש בקוד קיים עבור ישומיים שונים תוך שמירה על אותנטיות והתכונות הייחודיות בכל יישום .
          </p>

          <a href="#" >
            <img class="img-fluid" src="{% static 'blog/13.png' %}" alt="">
          </a>


          <h2 class="section-heading" style="text-align: right;">פשטות וקלות.</h2>
          <p class="text-right">
            Django מבוססת על שפת התכנות של Python שכיום היא השפה הפופולרית ביותר והוגדרה ע"י רוב המפתחים כשפה הקלה ביותר ללימוד.
            Django מתוחזקת על ידי קהילה גדולה של מפתחים והמשמעות היא שאנו יכולים למצוא תשובות לבעיות בקלות ובמהירות.
          </p>

          <h2 class="section-heading" style="text-align: right;">אבטחה</h2>
          <p class="text-right">
            אחת היתרונות הגדולים ביותר כיום של django למול מתחריה היא מערכת האבטחה המתקדמת המובנת בה, וחוסכת לנו כמפתחים את הצורך ליישם תכונות אבטחה בצורה ידנית.
            תיקוני אבטחה תכופים משולבים בגרסאות המופצות ע"י Django וזאת בהתאם להתפתחות הטכנולוגית בתחום כדי להבטיח כי כל תקני האבטחה העדכניים מיושמים.
          </p>

          <h2 class="section-heading" style="text-align: right;">אלו ישומיים מתאים לבנות בעזרת Django</h2>
          <ul class="list-styled" style="text-align: right;">
              <li> ישומיים מבוססי לקוח - CRM.</li>
              <li> ישומיים מבוססי דאטה הכוללים יכולות אנליטיקה מתקדמות.</li>
              <li> Django  לעומת מתחריה מיועדת לישומיים בסדר גודל בינוני וגדול ופחות מתאימה ליישומים קטנים. Django מאפשרת לבנות ישומיים מגוונים:
              </li>
              <li>ישומיי קניות</li>
              <li>ישומיי אדמינסטרציה למערכות תפעוליות.</li>
              <li>ישומיי לימוד מכונה (Machine learning)</li>
              <li> ישומיי בלוג</li>
          </ul>

           <h2 class="section-heading" style="text-align: right;">קהילה</h2>
          <p class="text-right">
            קהילת Django היא אחת הקהילות הגדולות והטובות ביותר כיום ומנוהלת על ידי קרן התוכנה של Django .
            לינקים לקהילות ואתרי ידע מובילים,

              <br><a href="https://www.djangoproject.com/community/">djangoproject</a><br>

              <a href="https://www.codementor.io/community/topic/django">codementor</a><br>
              <a href="https://djangopackages.org/">djangopackages</a><br>
              <a href="https://ccbv.co.uk/">ccbv</a>
          </p>

           <h2 class="section-heading" style="text-align: right;"> החברות שאימצו את פלטפורמת Django</h2>

          <img src="{% static 'blog/django_uses.png' %}" style="width:100%;">

        </div>
      </div>
    </div>
  </article>

  <hr>

<section class="copyright py-4 text-center text-black">
            <div class="container"><small>Copyright © Django Lab 2020</small></div>
</section>
{% endblock %}

blog/templates/nav.html
<nav class="navbar sticky-top navbar-dark bg-dark">
  <a class="navbar-brand" href="/home">    הבית של DjangoLab </a>

</nav>

blog/templates/navblog.html
  {% load static %}
        <!-- Navigation-->

<nav class="navbar navbar-expand-xl bg-white sticky-top" id="mainNav">
    <div class="collapse navbar-collapse">
        <div class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" style="color:black" href="home">בית</a>
            </li>
        </div>
    </div>
    <a class="nav-item" href="#">
        <img src="{% static 'home/lab.png' %}" >
    </a>
</nav>


        <!-- Masthead-->

forum/templates/forum.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section>
    <div class="jumbotron jumbotron-fluid text-center" style ="background-color:#1ABC9C; color: white;">
        <div class="container">
            <h1 class="display-4">Django Forum</h1>
        </div>
    </div>
</section>

<div class="container">
    <div class="row" >
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#ModalLoginForm">
            שאל את הפורום
        </button>
    </div>
</div>
<div class="container" >
    {% for forum in object_list %}
    <div class="row" >
        <div class="col-10">
            <div class="col align-self-center">
                <div class="card-body">
                    <blockquote class="blockquote mb-0">
                        <p>{{ forum.forum_title }}</p>
                        <footer class="blockquote-footer">Someone famous in </footer>
                    </blockquote>
                    <span class="badge badge-primary badge-pill">1</span>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- pagination-->

</div>

<!-- pagination -->
<div class="container" align="center">

    <ul class="pagination">
         {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1"> &laquo; first</a>
            <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}"> &laquo; previous</a>
            <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% endif %}


        <li class="page-item">
            <p class="page-link">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </p>
        </li>

        {% if page_obj.has_next %}

        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}"> &laquo; next</a>
            <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}"> &laquo; last</a>
            <span aria-hidden="true">&laquo;</span>
            </a>
        </li>


        {% endif %}


    </ul>

</div>


<!-- form for new question-->
<div id="ModalLoginForm" class="modal fade">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title">שאל את הפורום</h1>
            </div>
            <div class="modal-body">
                <form action= "{% url 'forum:topic'  %}"  role="form" method="POST" id="massege">
                    {% csrf_token %}
                    <input type="hidden" name="_token" value="">
                    <div class="form-group">
                        <label class="control-label">כותרת</label>
                        <div>
                            <input type="text" class="form-control input-lg" name="forum_title" value="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">תוכן</label>
                        <div>
                            <textarea class="form-control" name="forum_text" placeholder="Required example textarea" ></textarea>
                        </div>
                        <p>ניתן להרחיב את שדה ההזנה</p>
                    </div>
                    <div class="form-group">
                        <div>
                            <button type="submit" class="btn btn-success">שלח</button>
                        </div>
                    </div>
                </form>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

{% endblock %}"

forum/templates/nav.html
<nav class="navbar sticky-top navbar-dark bg-dark">
  <a class="navbar-brand" href="/home">    הבית של DjangoLab </a>
</nav>

forum/templates/newtopic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

home/templates/home.html
<!DOCTYPE html>
<html dir="rtl"  lang="en">
{% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="django israel" />
        <meta name="keywords" content="django, python,django israel, דגאנגו">
        <meta name="author" content="ofer elzam-toporik" />
        <link rel="shortcut icon" href="{% static 'home/logo.png' %}">
        <title>Lab4Django</title>
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.12.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <!--link href="css/styles.css" rel="stylesheet" /-->
        <link rel="stylesheet" type="text/css" href="{% static 'home/styles.css' %}" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
           {% include "navhome.html" %}
        <!-- Masthead-->
        <header class="masthead bg-primary text-white text-center">
            <div class="container d-flex align-items-center flex-column">
                <!-- Masthead Avatar Image--><img class="masthead-avatar mb-5" src="assets/img/avataaars.svg" alt="" /><!-- Masthead Heading-->
                <h1 class="masthead-heading text-uppercase mb-0">Django</h1>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Masthead Subheading-->
                <p class="masthead-subheading font-weight-light mb-"> האתר לקידום דג'נגו בישראל  </p>
                <p class="masthead-subheading font-weight-light mb-0"> Python, Django and Data</p>
            </div>
        </header>
        <!-- blog Section-->
        <section class="page-section portfolio" id="blog">
            <div class="container">
                <!-- blog Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">בלוג</h2>
                <!-- Icon Divider-->
                <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- blog Grid Items-->

                <div class="card text-center">
                        <div class="card-header">Django Lab</div>
                        <div class="card-body">
                           <h5 class="card-title">{{title1}}</h5>
                            <p class="card-text">{{desc1}}.</p>
                           <a href="#" class="btn btn-primary">קרא עוד</a>
                         </div>
                        <div class="card-footer text-muted">Django Lab</div>
                </div>
                <br>
                <div class="card text-center">
                        <div class="card-header">Django Lab</div>
                        <div class="card-body">
                           <h5 class="card-title">{{title2}}</h5>
                            <p class="card-text">{{desc2}}.</p>
                           <a href="/blog/1" class="btn btn-primary">קרא עוד</a>
                         </div>
                        <div class="card-footer text-muted">Django Lab</div>
                </div>
                <br>
                <br>
                <a class="btn btn-primary btn-lg btn-block" href="/blog" role="button">עבור לבלוג המלא</a>

            </div>
        </section>
        <!-- About Section-->
        <section class="page-section bg-primary text-white mb-0" id="about">
            <div class="container">
                <!-- About Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-white">Django Lab</h2>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- About Section Content-->
                <div class="row">
                    <p class="text-justify text-wrap">שמי עופר ואני מפתח תוכנה ומנהל פרוייקטים בכיר, כיום אני מפתח תוכנה נלהב שעובד עם פייתון דג'אנגו והמון דאטה.<br>
                     יצרתי את הבלוג הזה כדי לשתף קצת מהמחשבות והניסיון שלי ובעיקר מיכוון שאני מאוד מאמין שהעולם המרתק הזה עדיין בתחילתו והיכולות של הפלטפורמה המדהימה הזו הן מאוד רחבות.<br>
                       הבלוג ינסה להציג על קצה המזלג פתרונות ודוגמאות שבהם אני נתקל תוך דגש על שילוב הפלטפורמה יחד עם נושאי חדשנות מובילים המאפשרים להרחיב את הפתרון הטכנולוגי.<br>
                     מעבר לכתיבת הבלוג אשמח לשיתופי פעולה ורעיונות נוספים בעולם Django&Python&Data</p>
                </div>
                <!-- About Section Button-->

            </div>
        </section>
        <!--services section -->
        <section class="page-section portfolio" id="services">
            <div class="container">
                <!-- Portfolio Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">השירות שלנו</h2>
                <!-- Icon Divider-->
                <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- services Grid Items-->
                <div class="card-deck">
                    <div class="card">
                        <img src="{% static 'blog/3.jpg' %}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h4 style="text-align:right;color:Tomato;">שיתופי פעולה</h4>
                            <h5 style="text-align:right"> מוזמנים לפנות אלינו לבחינת שיתופי פעולה אפשריים ולכול רעיון ומיזם</h5>

                        </div>
                    </div>
                    <div class="card">
                        <img src="{% static 'blog/learn.jpg' %}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h4 style="text-align:right;color:Tomato;">יעוץ ולימוד</h4>
                            <h5 style="text-align:right">העברת ידע, הכשרה,לימוד אישי וקבוצתי וייעוץ בהקמה ותפעול</h5>

                        </div>
                    </div>
                    <div class="card">
                        <img src="{% static 'blog/ask.png' %}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h4 style="text-align:right;color:Tomato;">פורום לשאלות ותשובות</h4>
                            <h5 style="text-align:right"> פורום לשיתוף מידע והעלאת סוגיות ושאלות. <br>אנו נשתדל לענות בהקדם </h5>

                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Contact Section-->
        <section class="page-section bg-primary text-white mb-0" id="contact" >
            <div class="container">
                <!-- Contact Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">צור קשר</h2>
                <!-- Icon Divider-->
                <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>

                <!-- Contact Section Form-->
                <div class="row">
                    <div class="col-lg-8 mx-auto">
                        <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19.-->
                        <form action="/contactus/" method="POST" id="contactForm" name="sentMessage" >
                            {% csrf_token %}
                            <div class="form-group">
                                  <label for="id_email_name">שם</label>
                                  <input type="text" class="form-control" id="id_email_name" name="email_name" >
                             </div>

                            <div class="form-group">
                                  <label for="id_email_email">כתובת מייל</label>
                                  <input type="email" class="form-control" id="id_email_email" name="email_email" placeholder="name@example.com">
                             </div>

                            <div class="form-group">
                                  <label for="id_email_phone">טלפוון</label>
                                  <input type="text" class="form-control" id="id_email_phone" name="email_phone" placeholder="050">
                             </div>

                             <div class="form-group">
                                  <label for="id_email_text">תוכן ההודעה</label>
                                  <textarea name="email_text" class="form-control" cols="40" rows="10" required id="id_email_text"></textarea>
                             </div>

                            <div class="form-group"><button class="btn btn-secondary btn-xl" id="sendMessageButton" type="submit">שלח</button></div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="footer text-center">
            <div class="container">
                <div class="row">
                    <!-- Footer Location-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">מיקום</h4>
                        <p class="lead mb-0">נס ציונה <br />פארק המדע</p>
                    </div>
                    <!-- Footer Social Icons-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Around the Web</h4>
                        <a class="btn btn-outline-light btn-social mx-1" href="#"><i class="fab fa-fw fa-facebook-f"></i></a><a class="btn btn-outline-light btn-social mx-1" href="#"><i class="fab fa-fw fa-twitter"></i></a><a class="btn btn-outline-light btn-social mx-1" href="#"><i class="fab fa-fw fa-linkedin-in"></i></a><a class="btn btn-outline-light btn-social mx-1" href="#"><i class="fab fa-fw fa-dribbble"></i></a>
                    </div>
                    <!-- Footer About Text-->
                    <div class="col-lg-4">
                        <h4 class="text-uppercase mb-4"> תמיכה ומענה</h4>
                        <p class="lead mb-0">lab4django@gmail.com </p>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Copyright Section-->
        <section class="copyright py-4 text-center text-white">
            <div class="container"><small>Copyright © Django Lab 2020</small></div>
        </section>
        <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes)-->
        <div class="scroll-to-top d-lg-none position-fixed">
            <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top"><i class="fa fa-chevron-up"></i></a>
        </div>

        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <!-- Contact form JS-->
        <!--<script src="assets/mail/jqBootstrapValidation.js"></script>-->
        <!--<script src="assets/mail/contact_me.js"></script>-->
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>